### ISSUE TITLE
Cancel Button not working since iOS13

### ISSUE THREAD

**Issue by RuairiOliver** [morenoh149/react-native-contacts#467] opened 2019-12-13 17:30 UTC
Hi,

I'm using the latest version of this library and calling Contacts.openContactForm. 

I've noticed since iOS 13 pressing cancel no longer works. It masks the screen but the modal isn't dismissed. 

If I can get the keyboard to dismiss(by pressing delete buttons or clicking the contact photo) then the cancel button works from then but while the keyboard is visible cancel won't do anything except mask the screen.

If anyone has any ideas on how to resolve this it would be great.

Thanks

**Comment by joaonew** [comment] 2019-12-19 19:49
I have the same problem on my application, the cancel button is not working, only option is to save to leave the screen.

Any help? 

+1

**Comment by andriinegustorov** [comment] 2019-12-20 15:19
the same here

**Comment by mlc** [comment] 2020-01-07 16:31
This appears to be a bug in iOS itself; see e.g. [this StackOverflow post](https://stackoverflow.com/questions/58178882/keyboard-overlaying-action-sheet-in-ios-13-1-on-cncontactviewcontroller). I can confirm the behavior I'm seeing using `react-native-contacts` is the same as that described in the post: it works okay on iOS 13.0, but not on iOS 13.1–13.3.

**Comment by Peretz30** [comment] 2020-03-25 11:40
Fixed in iOS 13.4

**Closed** 2020-03-25 18:56 UTC
Labels: good first issue

**Comment by Dror-Bar** [comment] 2020-03-29 08:47
@Peretz30 Just to clarify, does this mean the bug is not related to this library, there is no workaround, and we do nothing because the bug will resolve itself when users upgrade their IOS?

**Comment by Peretz30** [comment] 2020-03-29 10:39
@Dror-Bar yes, it is.
